### ISSUE TITLE
新手小白，请多指教

### ISSUE THREAD

**Issue by michaelChengSY** [Jervis2049/vite-plugin-crx-mv3#1]
您好！fork了您的项目，感觉很不错！最近需要做chrome插件，但是对于前端技术，本人属于小白“菜”！
不知道可不可以有时间，增加一个相对全一些的demo！方便我这种“菜”上手，如果打扰您，真是不好意思！

**Comment by Jervis2049** [comment]
您好，感谢关注。目前这个vite插件还有一些场景尚未覆盖，但已满足一般的开发了。里面也有不少demo，有点基础的应该不难理解，后续我再补充一个hello world例子。您是完全的新手吗？现在可以运行项目吗？是否有报错？

**Comment by Jervis2049** [comment]
> 您好！fork了您的项目，感觉很不错！最近需要做chrome插件，但是对于前端技术，本人属于小白“菜”！ 不知道可不可以有时间，增加一个相对全一些的demo！方便我这种“菜”上手，如果打扰您，真是不好意思！

您好，感谢关注。目前这个vite插件还有一些场景尚未覆盖，但已满足一般的开发了。里面也有不少demo，有点基础的应该不难理解，后续我再补充一个hello world例子。您是完全的新手吗？现在可以运行项目吗？是否有报错？

**Comment by michaelChengSY** [comment]
您好！

非常感谢您的回复，

是的，完全新手！

1、example中的一些项目我可以启动，不过用的是pnmp run dev命令！在我的本地环境，使用您文档中的命令报异常，看您的说明中没有run关键字，我也不知道为什么！
2、我准备基于vue开发，但是我不清楚如何基于您的框架去一步一步的集成进来。
3、看您这个前端的框架原理，短时间来说，对我个人而言学习路线有些陡峭！我目前比较棘手的问题是：如何像在正常的vue项目下开发，比如，每个相关的文件在您的框架下，我需要怎么处理等！
4、如果有一个完整流程的示例，对于我参考学习，会帮助很大！非常感谢！
5、希望可以通过您的这个项目，让我学习的更多！

**Comment by Jervis2049** [comment]
> 您好！
> 
> 非常感谢您的回复，
> 
> 是的，完全新手！
> 
> 1、example中的一些项目我可以启动，不过用的是pnmp run dev命令！在我的本地环境，使用您文档中的命令报异常，看您的说明中没有run关键字，我也不知道为什么！ 2、我准备基于vue开发，但是我不清楚如何基于您的框架去一步一步的集成进来。 3、看您这个前端的框架原理，短时间来说，对我个人而言学习路线有些陡峭！我目前比较棘手的问题是：如何像在正常的vue项目下开发，比如，每个相关的文件在您的框架下，我需要怎么处理等！ 4、如果有一个完整流程的示例，对于我参考学习，会帮助很大！非常感谢！ 5、希望可以通过您的这个项目，让我学习的更多！

example/vue-crx 这个例子如果剔除掉Chrome扩展的一些内容，其实就是正常的vue项目结构了，你可以添加components目录等等内容进来。你用的vue2还是vue3？例子使用的是最新的vue3。三两句可能完全清楚你的疑问，如果需要，可以留个WeChat私聊，我帮你解答。

**Comment by Jervis2049** [comment]
> 您好！
> 
> 非常感谢您的回复，
> 
> 是的，完全新手！
> 
> 1、example中的一些项目我可以启动，不过用的是pnmp run dev命令！在我的本地环境，使用您文档中的命令报异常，看您的说明中没有run关键字，我也不知道为什么！ 2、我准备基于vue开发，但是我不清楚如何基于您的框架去一步一步的集成进来。 3、看您这个前端的框架原理，短时间来说，对我个人而言学习路线有些陡峭！我目前比较棘手的问题是：如何像在正常的vue项目下开发，比如，每个相关的文件在您的框架下，我需要怎么处理等！ 4、如果有一个完整流程的示例，对于我参考学习，会帮助很大！非常感谢！ 5、希望可以通过您的这个项目，让我学习的更多！

example/vue-crx 这个例子如果剔除掉Chrome扩展的一些内容，其实就是正常的vue项目结构了，你可以添加components目录等等内容进来。你用的vue2还是vue3？例子使用的是最新的vue3。三两句可能不完全清楚你的疑问，如果需要，可以留个WeChat私聊，我帮你解答。

**Comment by michaelChengSY** [comment]
好的，非常感谢！
438035519@qq.com是我的私人邮箱，wechat我们可以在邮件中确认！

**Comment by Jervis2049** [comment]
好的。可以加下我微信 Jervis2014



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月2日(周五) 中午1:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jervis2049/vite-plugin-crx-mv3] 新手小白，请多指教 (Issue #1)




 
好的，非常感谢！
 ***@***.***是我的私人邮箱，wechat我们可以在邮件中确认！

**Comment by Jervis2049** [comment]
> 好的，非常感谢！ [438035519@qq.com](mailto:438035519@qq.com)是我的私人邮箱，wechat我们可以在邮件中确认！

回你邮件了，请查收
