### ISSUE TITLE
manifest->background 设置type:"module"，打包后自动被去除

### ISSUE THREAD

**Issue by AIG-CN** [Jervis2049/vite-plugin-crx-mv3#15]
起因是我在background引入第三方模块，报错Uncaught SyntaxError: Cannot use import statement outside a module。
然后尝试在background {
     "service_worker": "background.js",
      "type": "module" // 增加 module
}
但是打包出来的manifest中 type:"module" 被自动去除，请问大佬这个可以解决吗，不然每次都得自己手动补上

**Comment by Jervis2049** [comment]
最新的版本已经修复。

**Comment by Jervis2049** [comment]
#14 这个issue提过了。
