### ISSUE TITLE
插件无法运行

### ISSUE THREAD

**Issue by 724493602** [Jervis2049/vite-plugin-crx-mv3#25]
`import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import crx from 'vite-plugin-crx-mv3'

export default defineConfig({
    plugins: [
        vue(),
        crx({
            manifest: './manifest.json'
        }),
    ],
})`

报错
error when starting dev server:
TypeError: crx is not a function

**Comment by 724493602** [comment]
插件0.1.3版本

**Comment by Jervis2049** [comment]
根据描述无法定位问题，希望提供一个可以复现这个问题的demo。

**Comment by Js-Man-H5** [comment]
crx.default({....}) 就可以了

**Comment by Jervis2049** [comment]
v1.0.4已修复

**Comment by Jervis2049** [comment]
v0.1.4已修复
