### ISSUE TITLE
import 无法直接引入包

### ISSUE THREAD

**Issue by Js-Man-H5** [Jervis2049/vite-plugin-crx-mv3#28]
打印出来是这样的 { default: [Getter] }

**Comment by Js-Man-H5** [comment]
使用需要这样 X.default()，有点变扭

**Comment by Jervis2049** [comment]
你是不是这样写了 const crx = require("vite-plugin-crx-mv3");

**Comment by Js-Man-H5** [comment]
不是的,是这样的 import crx from 'vite-plugin-crx-mv3'

**Comment by Js-Man-H5** [comment]
https://github.com/Jervis2049/vite-plugin-crx-mv3/issues/25 这个issues也是同样的问题

**Comment by Jervis2049** [comment]
你node的版本是？ 我这边用的v16正常。

**Comment by Jervis2049** [comment]
刚刚发现package.json 加上"type": "module"也会报这个错。

**Comment by Jervis2049** [comment]
v0.1.4已修复
