### ISSUE TITLE
你好大佬有没有element-plus的示例

### ISSUE THREAD

**Issue by djwIlo** [Jervis2049/vite-plugin-crx-mv3#3]

**Comment by Jervis2049** [comment]
你好，element-plus的示例没有，写不来那么多。有个ant-design的（examples/crx-vue-antd-bookmarks），应该也差不多，你可以改下。

**Comment by djwIlo** [comment]
好的我看着改一下

**Comment by s836064858** [comment]
https://github.com/s836064858/chrome-extension-vite
基于大佬的vite插件 集成了element-plus的一点点代码
