### ISSUE TITLE
Sourcemap is likely to be incorrect: a plugin (vite-plugin-crx-mv3) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

### ISSUE THREAD

**Issue by JinLongy** [Jervis2049/vite-plugin-crx-mv3#35]
大佬 我这build的时候 Sourcemap is likely to be incorrect: a plugin (vite-plugin-crx-mv3) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
出这个提示 然后打包后的content.js还是原先的代码 然后content里面的vue文件中的css 并没有打包到最后的文件中 打包后的manifest文件也没有注入css

**Comment by Jervis2049** [comment]
你好。可以提供一个复现的demo吗

**Comment by Jervis2049** [comment]
v0.1.7修复了 麻烦试下

**Comment by JinLongy** [comment]
大佬 我试了 打包可以了 但是 我在content中写的样式没有在打包后的文件生效 我看已经打出来对应的css文件
![image](https://github.com/Jervis2049/vite-plugin-crx-mv3/assets/44226522/d69e27aa-f4f9-4e71-ac21-7889ee8ce5eb)

**Comment by Jervis2049** [comment]
> 大佬 我试了 打包可以了 但是 我在content中写的样式没有在打包后的文件生效 我看已经打出来对应的css文件 ![image](https://private-user-images.githubusercontent.com/44226522/295860252-d69e27aa-f4f9-4e71-ac21-7889ee8ce5eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMTc5NDksIm5iZiI6MTcwNTAxNzY0OSwicGF0aCI6Ii80NDIyNjUyMi8yOTU4NjAyNTItZDY5ZTI3YWEtZjRmOS00ZTcxLWFjMjEtNzg4OWVlOGNlNWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAwMDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYmI4ZGMxYzJkYzQ4NTA0NzhlMzdlNjcwNjAxOWNkOTQ1OTA5NzI2NjVmYTNiM2YzYTQ0NGE0ZjhhMDNiYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b49sttI7umdGmEvL0Oh_qs7gdIHu2vWM4CHMPncqubo)

我在examples目录下都例子应该是可以的。我还是没法根据你提供的信息定位到问题，如果方便最好可以提供一个可复现的demo，你可以剔除其它业务代码。

**Comment by JinLongy** [comment]
打包前
manifest.json文件
`{
    "manifest_version": 3,
    "homepage_url": "xxx",
    "name": "xxx平台",
    "description": "xxx平台",
    "version": "1.0.0",
    "icons": {
        "16": "assets/icon/icon-16.png",
        "32": "assets/icon/icon-32.png",
        "48": "assets/icon/icon-48.png",
        "64": "assets/icon/icon-64.png",
        "128": "assets/icon/icon-128.png"
    },
    "action": {
        "default_title": "xxx平台",
        "default_popup": "./options.html",
        "default_icon": {
            "16": "assets/icon/icon-16.png",
            "32": "assets/icon/icon-32.png",
            "48": "assets/icon/icon-48.png",
            "64": "assets/icon/icon-64.png",
            "128": "assets/icon/icon-128.png"
        }
    },
    "content_security_policy": {
        "extension_pages": "script-src 'self'; script-src-elem 'self' http://127.0.0.1:17681; object-src 'self'; frame-ancestors 'none';"
    },
    "externally_connectable": {
        "ids": ["*"]
    },
    "permissions": [
        "storage",
        "activeTab",
        "scripting",
        "webRequest",
        "tabs",
        "notifications",
        "contextMenus",
        "declarativeNetRequest",
        "declarativeNetRequestFeedback"
    ],
    "host_permissions": [
        "http://127.0.0.1:17681/*"
    ],
    "declarative_net_request": {
        "rule_resources": [
            {
                "id": "ruleset_1",
                "enabled": true,
                "path": "./rules.json"
            }
        ]
    },
    "background": {
        "service_worker": "./background.ts",
        "type": "module"
    },
    "content_scripts": [
        {
            "matches": ["<all_urls>"],
            "all_frames": true,
            "js": ["./injection/content.ts"]
        }
    ],
    "web_accessible_resources": [
        {
            "matches": ["<all_urls>"],
            "resources": ["assets/*"]
        }
    ],
    "commands": {
        "_execute_action": {
            "suggested_key": {
                "windows": "Alt+Shift+N",
                "mac": "Alt+Shift+N",
                "chromeos": "Alt+Shift+N",
                "linux": "Alt+Shift+N"
            }
        }
    },
    "options_page": "./index.html"
}
`
注入 injection/App.vue
`<template>
    <div class="crx-popup-wrapper">
    123
        <div class="version">{{ versionCode }}</div>
    </div>
</template>

<script lang="ts" setup>
import { ref, computed } from 'vue'
import _ from 'lodash'
import { Button } from 'ant-design-vue'
// @ts-ignore
import config from '@/config/index'

const versionCode = computed(() => {
    return 'V' + config.versionCode
})
</script>

<style>
#crx-popup-app {
    width: 300px;
    height: 400px;
}
</style>
<style scoped lang="less">
.crx-popup-wrapper {
    width: 100%;
    height: 100%;
    border: 1px solid #f5f5f5;
    border-radius: 12px;
    position: relative;
    background-image: url('../assets/bg.png');
    background-size: 100% 100%;
    background-repeat: no-repeat;
    .version {
        position: absolute;
        right: 20px;
        bottom: 20px;
        font-size: 12px;
        color: #666666;
    }
}
</style>
`
注入injection/content.ts
`import { createApp } from "vue";
import '@/styles/index.less'
import '../style.css';
import 'ant-design-vue/dist/antd.css';
import App from './App.vue';

window.onload = async () => {
    const el = document.querySelector('body');
    if (el) {
        el.insertAdjacentHTML(
            'afterend',
            '<div id="crx-popup-app"></div>',
        );
        const app = createApp(App)
        app.mount('#crx-popup-app');
    }
}`

**Comment by JinLongy** [comment]
打包前 manifest.json
[manifest.json](https://github.com/Jervis2049/vite-plugin-crx-mv3/files/13916215/manifest.json)
src\injection\App.vue
[App.txt](https://github.com/Jervis2049/vite-plugin-crx-mv3/files/13916237/App.txt)
src\injection\content.ts
[content.txt](https://github.com/Jervis2049/vite-plugin-crx-mv3/files/13916239/content.txt)

**Comment by JinLongy** [comment]
打包后
![image](https://github.com/Jervis2049/vite-plugin-crx-mv3/assets/44226522/20738da3-d02f-4f0e-ae0a-6779f8dae6da)
manifest.json
[manifest.json](https://github.com/Jervis2049/vite-plugin-crx-mv3/files/13916330/manifest.json)
![image](https://github.com/Jervis2049/vite-plugin-crx-mv3/assets/44226522/032cfb30-3521-49fb-a721-56b5b0be73ee)
但是在页面调试并不能看到样式
![image](https://github.com/Jervis2049/vite-plugin-crx-mv3/assets/44226522/7056b5fa-aea8-4cb4-9008-dc76abb127c7)
