### ISSUE TITLE
你好 ant 组件跟 element-plus组件在content-scripts页面个别组件无法加载

### ISSUE THREAD

**Issue by djwIlo** [Jervis2049/vite-plugin-crx-mv3#4]
![image](https://user-images.githubusercontent.com/69334634/220851254-5c69668e-4fc9-4cec-baec-31cfa1e18204.png)
popup页面成功使用例如form表单，选择框等复杂组件
![image](https://user-images.githubusercontent.com/69334634/220851600-cae88975-0170-417d-a69e-f53b7ffef067.png)
在content-scripts脚本注入页面使用form 选择框等组件报错，只能使用简单的button等组件，
大佬有办法解决吗

**Comment by Jervis2049** [comment]
我也复现这个问题了，等有时间再仔细看看。

**Comment by djwIlo** [comment]
好滴，大佬幸苦

**Comment by Jervis2049** [comment]
v0.1.0-beta.0发布了 ，这个问题应该也修复了，有空可以帮忙测试一下，谢谢。
