### ISSUE TITLE
建议同步package.json 与 manifest.json 中的版本号

### ISSUE THREAD

**Issue by rhinonan** [Jervis2049/vite-plugin-crx-mv3#8]
当进行工程化的开发时，很多工具只对package.json 有着较好的支持。
比如 standard-version 进行版本发布，这个工具只会自动修改packages.json 的中的版本，而manifest 中需要手动修改。

建议当manifest version 设置为auto，或者未设置，或者通过vite.config 中的配置来进行控制。

**Comment by Jervis2049** [comment]
这样吧，当manifest version 设置为auto，或者未设置时，build的时候我获取package.json的version赋值给manifest version。下个版本我优化一下这个。

**Comment by rhinonan** [comment]
nice,  给大佬添麻烦了
