### ISSUE TITLE
怎么新建配置页面，并变成更正确路径，

### ISSUE THREAD

**Issue by hzb888** [Jervis2049/vite-plugin-crx-mv3#9]
浏览器插件a想写一个配置页面，但是路径每次都被变成加上了随机数，我写代码跳转页面也就失效了。 那还有什么办法自定义一个页面并获取到路径吗

**Comment by hzb888** [comment]
extension://kcggnpflpknemmiocgkbcinignikemll/popup.html   浏览器的配置页面。可以理解一个新的页面， 类似于其他扩展的前面的地址。  但是vite 会改文件名。而且html 还不知道怎么编译 ==

**Comment by Jervis2049** [comment]
这个配置页面你或许可以取个别的名字，因为popup一般是点击扩展图片弹出的那个页面。你可以命名options，然后在manifest.json配置
```
  "options_page": "../options.html"
```
跳转代码：
```
function open(){
  let url = chrome.runtime.getURL('options.html')
  chrome.tabs.create({ url })
}

```

**Comment by hzbnb** [comment]
好的 谢谢了🙏
